name: Context testing
on: 
  workflow_dispatch:

jobs:
  dump_contexts_to_log:
   runs-on: ubuntu-latest
   steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
  get_username:
    runs-on: ubuntu-latest
    outputs:
      username: ${{ steps.get_username.outputs.username}}
    steps:
      - name: Get the username
        id: get_username
        run: echo "::set-output name=username::${{ github.triggering_actor }}"
  echo_username:
    needs: get_username
    runs-on: ubuntu-latest
    if: ${{ github.run_attempt > 1}}
    steps:
      - name: Echo the username
        run: echo "Rerun number ${{github.run_attempt}} trigered by  ${{ needs.get_username.outputs.username }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: rerun
          path: artifact.txt